# Generated by Django 4.0.5 on 2022-07-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_contacto111_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='dudas',
            new_name='mensaje',
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']], default=1),
            preserve_default=False,
        ),
    ]
