# Generated by Django 4.0.5 on 2022-07-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contacto_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_consulta',
        ),
    ]
